learning_templates/basic_app/urls.py
from django.urls import path, include
from basic_app import views

#TEMPLATE TAGGING
app_name = 'basic_app'
urlpatterns = [
    path('other/', views.other, name='other'),
    path('relative_url_templates/', views.relative_url_templates, name='relative_url_templates'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basic_app/',include('basic_app.urls')),
    # path('other', views.other, name='other'),
    # path('relative_url_templates', views.relative_url_templates, name='relative_url_template')
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'Hello world','number':100}
    return render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative_url_templates(request):
    return render(request,'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'admin:index'%}">Admin <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:other'%}">Other</a>
          </li>
        </ul>
    </nav>
    <p></p>
    <div class="container">
      <div class="jumbotron">
        {% block body_block %}
        {% endblock %}
      </div>
    </div>
  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
{% load my_extras %}
  {%block body_block%}
    <h1>WELCOME TO INDEX</h1>
    <h1>This is index.html page showing</h1>
    {{ text|cut:"world" }}
    {{ number|add:"99" }}
  {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
{% block body_block %}
    <h1>WELCOME TO OTHER</h1>
    <h2>This is an exmample of template inheritance</h2>
    <a href="{%url 'basic_app:relative_url_templates'%}">TO RELATIVE TEMPLATES PAGE</a>
{% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{%url 'basic_app:other'%}">TO THE OTHER PAGE</a>
    <a href="{% url 'admin:index'%}">GO TO ADMIN PAGE</a>
    <a href="{%url 'index' %}">GO TO INDEX PAGE</a>
  </body>
</html>